Webapp reports successful transaction even if the sender is not a co-sginer
Zilliqa/zilliqa-multisig-wallet pull request #28
Opened 2022-09-22 16:04 UTC by ashishnair-zil

1.) Webapp reports successful transaction even if the sender is not a co-sginer
Jira no: https://zilliqa-jira.atlassian.net/jira/software/projects/US/boards/11?selectedIssue=US-98

2022-10-10 04:15 UTC, inamirandaz commented on src/smartcontract/multisig_wallet.scilla.js
> +const CODE = `scilla_version 0
@ashishnair-zil is this change supposed to be here or this is from another PR/commit?

2022-10-10 04:16 UTC, inamirandaz commented on src/assets/style.scss
> +      width: 52px;
@ashishnair-zil this is not for this PR, right?

2022-10-10 04:16 UTC, inamirandaz commented on src/components/Wallet/NewTransaction.vue
> +          placeholder="Tag transition"
@ashishnair-zil this is not for this PR, right?

2022-10-10 04:16 UTC, inamirandaz requested changes
@ashishnair-zil can we remove the changes/commits not relevant to this PR?

2022-10-13 02:21 UTC, ashishnair-zil commented
Closing this PR as [PR 29](https://github.com/Zilliqa/zilliqa-multisig-wallet/pull/29) include this changes

2022-10-13 02:21 UTC, closed without merging